export const consts = {
    productForm: {
        title: "Cadastro de produto",
        nameLabel: "Nome do produto",
        descriptionLabel: "Descrição do produto",
        colorLabel: "Cor do produto",
        categoryLabel: "Categoria",
        priceLabel: "Preço",
        submitButton: "Cadastrar produto",
        successMessage: "Produto cadastrado com sucesso",
        errorMessage: "Erro ao cadastrar o produto. Tente novamente",
      },
      productTable: {
        title: "Lista de Produtos",
        nameHeader: "Nome",
        descriptionHeader: "Descrição",
        colorHeader: "Cor",
        categoryHeader: "Categoria",
        priceHeader: "Preço",
        promotionalPriceHeader: "Promoção",
        actionsHeader: "Ações",
        deleteButton: "Excluir",
      },
      productFilters: {
        nameFilterLabel: "Filtrar por nome",
        categoryFilterLabel: "Categorias",
        sortLabel: "Ordenar por",
        allCategories: "Todas as categorias",
        selectBy: "Selecionar",
        alphabetical: "Ordem Alfabética",
        priceAsc: "Menor preço",
        priceDesc: "Maior preço",
      },
      item: {
        smartphones: "Smartphones",
        furniture: "Móveis",
        eletronics: "Eletrônicos",
        portable_appliances: "Eletroportáteis",
        refrigerator: "Geladeiras",
      }
}